baseURL = "https://jloosli.github.io/explore-mounts/"
languageCode = "en-us"
title = "My New Hugo Site"

disableKinds = ["taxonomy", "term"]
ignoreErrors = ["error-disable-taxonomy"]

[module]
[[module.imports]]
path = "github.com/sindresorhus/modern-normalize"
disable = false
[[module.imports.mounts]]
source = "./modern-normalize.css"
#target = "assets/scss/_modern-normalize.scss" # What I'd like to do
target = "static/css/modern-normalize.css" # What works (although only

